---
# defaults file for server
user: digitalsoba
github_keys: https://github.com/digitalsoba.keys
common_packages:
  - ca-certificates
  - gnupg
  - htop
  - openssh-server
  - net-tools
  - python3
  - sudo
  - tmux
  - vim
apt_packages:
  - apt-transport-https
  - curl
  - gnupg-agent
  - software-properties-common
  - unattended-upgrades
sudogroup: "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' }}"
